name: Code Quality Check

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - main  

jobs:
  code_quality:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Step 3: Cache dependencies
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      # Step 5: Run code quality check
      - name: Run Flake8
        run: flake8 --max-line-length=110

      # Step 6: Annotate errors (optional, for better feedback)
      - name: Annotate errors if any
        if: failure()
        run: echo "Code quality check failed. Please fix the issues highlighted above."

