name: Test Code Pre-Deployment

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      DEBUG: ${{ secrets.DEBUG }}
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_STORAGE_BUCKET_NAME: ${{ secrets.AWS_STORAGE_BUCKET_NAME }}
      AWS_S3_REGION_NAME: ${{ secrets.AWS_S3_REGION_NAME }}

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # Step 3: Cache Poetry dependencies
      - name: Cache Poetry dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      # Step 4: Install Poetry
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          poetry --version

      # Step 5: Install dependencies using Poetry
      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-ansi

      # Step 6: Apply database migrations
      - name: Run makemigrations and migrate
        run: |
          poetry run python _file_sharing_app/manage.py makemigrations
          poetry run python _file_sharing_app/manage.py migrate

      # Step 7: Run tests with Poetry
      - name: Run tests
        run: |
          poetry run python _file_sharing_app/manage.py test --verbosity=2

      # Step 8: Annotate errors if tests fail
      - name: Annotate test errors
        if: failure()
        run: echo "Tests failed. Please review the output logs and fix the errors."
